import { Search, BriefcaseBusiness, FileText, Send, Sparkles, TrendingUp, Clock3, CheckCircle2 } from 'lucide-react'

const jobs = [
  { company: 'Nova Analytics', role: 'Senior Data Analyst', location: 'Remote · India', match: 94, salary: '₹14–18 LPA', source: 'Company Careers', status: 'Ready' },
  { company: 'Orbit Labs', role: 'Product Analyst', location: 'Bengaluru · Hybrid', match: 91, salary: '₹15–20 LPA', source: 'Indeed', status: 'Review' },
  { company: 'Vertex Systems', role: 'Business Analyst', location: 'Delhi NCR · Hybrid', match: 87, salary: '₹11–15 LPA', source: 'LinkedIn', status: 'CV Ready' },
]

export default function Home() {
  return <main className="min-h-screen bg-[#0b1020] text-white font-sans">
    <div className="flex min-h-screen">
      <aside className="w-64 border-r border-white/10 bg-[#0d1326] p-5 hidden md:block">
        <div className="flex items-center gap-3 mb-10"><div className="h-10 w-10 rounded-xl bg-indigo-500 flex items-center justify-center"><Sparkles size={20}/></div><div><div className="font-bold">JobPilot AI</div><div className="text-xs text-slate-400">Personal career agent</div></div></div>
        <nav className="space-y-2 text-sm">
          {['Dashboard','Job Search','Recommended','Applications','CV Builder','Cover Letters','Companies','Interviews','Analytics','AI Assistant'].map((x,i)=><div className={`px-3 py-2.5 rounded-lg ${i===0?'bg-white/10 text-white':'text-slate-400 hover:bg-white/5'}`} key={x}>{x}</div>)}
        </nav>
        <div className="absolute bottom-6 w-52 rounded-xl bg-indigo-500/10 border border-indigo-400/20 p-4"><div className="text-xs text-indigo-300">AUTOMATION</div><div className="mt-1 font-semibold">Job search is active</div><div className="mt-3 h-1.5 rounded-full bg-white/10"><div className="h-full w-4/5 rounded-full bg-indigo-400"/></div><div className="mt-2 text-xs text-slate-400">Next scan in 24 minutes</div></div>
      </aside>
      <section className="flex-1 p-6 md:p-10 max-w-7xl mx-auto w-full">
        <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8"><div><div className="text-sm text-indigo-300">Wednesday, August 19</div><h1 className="text-3xl md:text-4xl font-bold mt-1">Good morning 👋</h1><p className="text-slate-400 mt-2">Your AI job search is running.</p></div><button className="px-4 py-2.5 rounded-xl bg-indigo-500 hover:bg-indigo-400 font-semibold flex items-center gap-2"><Search size={18}/> Search jobs</button></header>
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">{[[BriefcaseBusiness,'Jobs found','127'],[TrendingUp,'Strong matches','34'],[FileText,'Applications ready','12'],[Send,'Submitted','7']].map(([I,label,value])=><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5" key={label as string}><I size={19} className="text-indigo-300"/><div className="text-2xl font-bold mt-4">{value as string}</div><div className="text-sm text-slate-400 mt-1">{label as string}</div></div>)}</div>
        <div className="grid xl:grid-cols-[1fr_330px] gap-6">
          <div className="rounded-2xl border border-white/10 bg-white/[.03] overflow-hidden"><div className="p-6 border-b border-white/10"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Top opportunities</h2><p className="text-sm text-slate-400 mt-1">AI-ranked jobs based on your profile</p></div><span className="text-sm text-indigo-300">View all →</span></div></div>{jobs.map(j=><div className="p-6 border-b border-white/10 last:border-0" key={j.company+j.role}><div className="flex flex-col md:flex-row md:items-center justify-between gap-5"><div className="flex gap-4"><div className="h-12 w-12 rounded-xl bg-white/10 flex items-center justify-center font-bold">{j.company[0]}</div><div><h3 className="font-semibold">{j.role}</h3><div className="text-sm text-slate-300 mt-1">{j.company}</div><div className="text-xs text-slate-500 mt-1">{j.location} · {j.salary}</div><div className="text-xs text-slate-500 mt-2">Source: {j.source}</div></div></div><div className="flex items-center gap-3"><div className="text-right"><div className="text-xl font-bold text-emerald-300">{j.match}%</div><div className="text-[11px] text-slate-500">MATCH</div></div><button className="px-3 py-2 rounded-lg bg-white/10 text-sm">{j.status}</button></div></div></div>)}</div>
          <div className="space-y-6"><div className="rounded-2xl border border-white/10 bg-gradient-to-br from-indigo-500/15 to-white/[.03] p-6"><div className="flex items-center gap-2 text-indigo-300 text-sm font-semibold"><Sparkles size={16}/> AI CAREER ASSISTANT</div><h3 className="text-xl font-bold mt-4">What should I apply to?</h3><p className="text-sm text-slate-400 mt-2">Ask about jobs, CV tailoring, matching, or your application strategy.</p><div className="mt-5 rounded-xl bg-black/20 border border-white/10 p-3 text-sm text-slate-400">Find remote Data Analyst jobs above ₹12 LPA…</div><button className="mt-3 w-full rounded-xl bg-indigo-500 py-2.5 font-semibold">Ask AI</button></div><div className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><h3 className="font-bold">Application pipeline</h3><div className="space-y-4 mt-5">{[['Shortlisted','18'],['CV generated','12'],['Ready to apply','8'],['Interview','3']].map(([a,b])=><div className="flex justify-between text-sm" key={a}><span className="text-slate-400">{a}</span><span className="font-semibold">{b}</span></div>)}</div></div><div className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><div className="flex items-center gap-2"><Clock3 size={17} className="text-indigo-300"/><h3 className="font-bold">Automation status</h3></div><div className="mt-4 text-sm text-slate-400">Job discovery is active. New matches will appear automatically.</div><div className="mt-4 flex items-center gap-2 text-sm text-emerald-300"><CheckCircle2 size={16}/> Running</div></div></div>
        </div>
      </section>
    </div>
  </main>
}
